
version: "3"
services:
  postgres:
    image: postgres:9.6
    container_name: "masterdev"
    environment:
      - POSTGRES_DB=masterdev
      - POSTGRES_USER=masterdev
      - POSTGRES_PASSWORD=masterdev
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
